EXEC SP_RENAME 'FP_FREIGHT_FORM.BACKHAUL_PALLET_RATE' , 'UBSWBS_BACKHAUL_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.CROSSDOCK_PALLET_RATE' , 'UBSWBS_CROSSDOCK_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_PFF_PFH_UPCHARGE' , 'UBSWBS_TOOL_PFF_PFH_UPCHARGE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_COOLER_FREEZER_UPCHARGE' , 'UBSWBS_TOOL_COOLER_FREEZER_UPCHARGE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_MARGIN_TARGET' , 'UBSWBS_TOOL_MARGIN_TARGET', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_FUEL_SURCHARGE' , 'UBSWBS_TOOL_FUEL_SURCHARGE', 'COLUMN'

--UCS

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_BACKHAUL_PALLET_RATE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_CROSSDOCK_PALLET_RATE DECIMAL(10,3) NULL   

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_PFF_PFH_UPCHARGE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_COOLER_FREEZER_UPCHARGE DECIMAL(10,3) NULL  

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_MARGIN_TARGET DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_FUEL_SURCHARGE DECIMAL(10,3) NULL 