EXEC SP_RENAME 'FP_FREIGHT_FORM.BACKHAUL_PALLET_RATE' , 'DEFAULT_BACKHAUL_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.CROSSDOCK_PALLET_RATE' , 'DEFAULT_CROSSDOCK_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_PFF_PFH_UPCHARGE' , 'DEFAULT_TOOL_PFF_PFH_UPCHARGE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_COOLER_FREEZER_UPCHARGE' , 'DEFAULT_TOOL_COOLER_FREEZER_UPCHARGE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_MARGIN_TARGET' , 'DEFAULT_TOOL_MARGIN_TARGET', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.TOOL_FUEL_SURCHARGE' , 'DEFAULT_TOOL_FUEL_SURCHARGE', 'COLUMN'

--UCS

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_BACKHAUL_PALLET_RATE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_CROSSDOCK_PALLET_RATE DECIMAL(10,3) NULL   

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_PFF_PFH_UPCHARGE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_COOLER_FREEZER_UPCHARGE DECIMAL(10,3) NULL  

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_MARGIN_TARGET DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_FUEL_SURCHARGE DECIMAL(10,3) NULL 


UPDATE dbo.FP_FREIGHT_FORM 
SET UCS_TOOL_FUEL_SURCHARGE = 1,
	UCS_CROSSDOCK_PALLET_RATE = 2,
	UCS_BACKHAUL_PALLET_RATE = 3,
	UCS_TOOL_COOLER_FREEZER_UPCHARGE = 4,
	UCS_TOOL_MARGIN_TARGET = 5,
	UCS_TOOL_PFF_PFH_UPCHARGE = 6

