


EXEC SP_RENAME 'FP_FREIGHT_FORM.DEFAULT_BACKHAUL_PALLET_RATE' , 'BACKHAUL_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.DEFAULT_CROSSDOCK_PALLET_RATE' , 'CROSSDOCK_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.DEFAULT_TOOL_PFF_PFH_UPCHARGE' , 'TOOL_PFF_PFH_UPCHARGE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.DEFAULT_TOOL_COOLER_FREEZER_UPCHARGE' , 'TOOL_COOLER_FREEZER_UPCHARGE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.DEFAULT_TOOL_MARGIN_TARGET' , 'TOOL_MARGIN_TARGET', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.DEFAULT_TOOL_FUEL_SURCHARGE' , 'TOOL_FUEL_SURCHARGE', 'COLUMN'


--UCS ROLLBACK
ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_BACKHAUL_PALLET_RATE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_CROSSDOCK_PALLET_RATE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_PFF_PFH_UPCHARGE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_COOLER_FREEZER_UPCHARGE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_MARGIN_TARGET;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_FUEL_SURCHARGE;

