EXEC SP_RENAME 'FP_FREIGHT_FORM.BACKHAUL_PALLET_RATE' , 'UBSWBS_BACKHAUL_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.CROSSDOCK_PALLET_RATE' , 'UBSWBS_CROSSDOCK_PALLET_RATE', 'COLUMN'

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UBSWBS_TOOL_PFF_PFH_UPCHARGE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UBSWBS_TOOL_COOLER_FREEZER_UPCHARGE DECIMAL(10,3) NULL  

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UBSWBS_TOOL_MARGIN_TARGET DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UBSWBS_TOOL_FUEL_SURCHARGE DECIMAL(10,3) NULL 

--UCS

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_BACKHAUL_PALLET_RATE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_CROSSDOCK_PALLET_RATE DECIMAL(10,3) NULL   

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_PFF_PFH_UPCHARGE DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_COOLER_FREEZER_UPCHARGE DECIMAL(10,3) NULL  

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_MARGIN_TARGET BIT DECIMAL(10,3) NULL 

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD UCS_TOOL_FUEL_SURCHARGE BIT DECIMAL(10,3) NULL 




----ROLBACK

EXEC SP_RENAME 'FP_FREIGHT_FORM.UBSWBS_BACKHAUL_PALLET_RATE' , 'BACKHAUL_PALLET_RATE', 'COLUMN'

EXEC SP_RENAME 'FP_FREIGHT_FORM.UBSWBS_CROSSDOCK_PALLET_RATE' , 'CROSSDOCK_PALLET_RATE', 'COLUMN'

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UBSWBS_TOOL_PFF_PFH_UPCHARGE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UBSWBS_TOOL_COOLER_FREEZER_UPCHARGE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UBSWBS_TOOL_MARGIN_TARGET;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UBSWBS_TOOL_FUEL_SURCHARGE;


--UCS ROLLBACK
ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_BACKHAUL_PALLET_RATE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_CROSSDOCK_PALLET_RATE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_PFF_PFH_UPCHARGE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_COOLER_FREEZER_UPCHARGE;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_MARGIN_TARGET;

ALTER TABLE FP_FREIGHT_FORM DROP COLUMN UCS_TOOL_FUEL_SURCHARGE;

