DROP TABLE dbo.FP_VENDOR_MERCHANDISERS
GO

CREATE TABLE [dbo].[FP_VENDOR_MERCHANDISERS](
	[FP_VENDOR_MERCHANDISERS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MERCHANDISER_ID] [bigint] NULL,
	[VENDOR_NUMBER] [varchar](20) NULL,
	[WHS_NUMBER] [bigint] NULL,
	[IS_DELETED] [bit] NULL,
	[DATE_CREATED] [datetime] NOT NULL,
	[DATE_MODIFIED] [datetime] NULL
) ON [PRIMARY]
GO

