USE [TMS]
GO

/****** Object:  Table [dbo].[FP_DEFAULT_CONFIG]    Script Date: 7/4/2022 11:12:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FP_DEFAULT_CONFIG](
	[FP_DEFAULT_CONFIG_ID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CROSSDOCK_PALLET_RATE] [decimal](10, 3) NULL,
	[BACKHAUL_PALLET_RATE] [decimal](10, 3) NULL,
	[SHUTTLE_RATE_PER_MILE] [decimal](10, 3) NULL,
	[FUEL_SURCHARGE] [decimal](10, 3) NULL,
	[ESTIMATED_LUMPER_EXPENSE] [decimal](10, 3) NULL,
	[ESTIMATED_ACCESSORIAL_EXPENSE] [decimal](10, 3) NULL,
	[ANTICIPATED_CROSSDOCK_LOAD_WEIGHT] [decimal](10, 3) NULL,
	[ANTICIPATED_TL_LOAD_WEIGHT] [decimal](10, 3) NULL,
	[ANTICIPATED_BACKHAUL_LOAD_WEIGHT] [decimal](10, 3) NULL,
	[MARGIN_TARGET] [decimal](10, 3) NULL,
	[PFF_PFH_UPCHARGE] [decimal](10, 3) NULL,
	[COOLER_FREEZER_UPCHARGE] [decimal](10, 3) NULL,
	[FP_ENGINE_MONTHS_BACK] [int] NULL,
	[SUPPLIER_SCREEN_MONTHS_BACK] [int] NULL,
	[PO_COUNT] [decimal](10, 3) NULL,
	[AVG_PO_WEIGHT] [decimal](10, 3) NULL,
	[AVG_PO_UNITS] [decimal](10, 3) NULL,
	[AVG_PO_PALLETS] [decimal](10, 3) NULL,
	[MARGIN_LOSS_REPORT_MONTHS_BACK] [int] NULL,
	[SOURCE_SYSTEM] [varchar](50) NULL,
 CONSTRAINT [PK_FP_DEFAULT_CONFIG] PRIMARY KEY CLUSTERED 
(
	[FP_DEFAULT_CONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


