ALTER TABLE dbo.FP_FREIGHT_FORM_VENDOR
ADD USE_EAST_BLENDED_FREIGHT_RATE BIT NOT NULL DEFAULT (0)

ALTER TABLE dbo.FP_FREIGHT_FORM_VENDOR
ADD AVERAGE_PO_CUBES DECIMAL (18,3) NULL


---REVERT
ALTER TABLE FP_FREIGHT_FORM_VENDOR DROP COLUMN USE_EAST_BLENDED_FREIGHT_RATE;

ALTER TABLE FP_FREIGHT_FORM_VENDOR DROP COLUMN AVERAGE_PO_CUBES;


--FP_FREIGHT_FORM_VENDOR_LOG
ALTER TABLE dbo.FP_FREIGHT_FORM_VENDOR_LOG
ADD USE_EAST_BLENDED_FREIGHT_RATE BIT NULL

--ALTER TABLE dbo.FP_FREIGHT_FORM_VENDOR_LOG
--ADD AVERAGE_PO_CUBES DECIMAL (18,3) NULL

---REVERT
ALTER TABLE FP_FREIGHT_FORM_VENDOR_LOG DROP COLUMN USE_EAST_BLENDED_FREIGHT_RATE;








--FP_FREIGHT_FORM
ALTER TABLE dbo.FP_FREIGHT_FORM
ADD HARCAR_BLENDED_FREIGHT_RATE DECIMAL(10,3)  

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD STKSGM_BLENDED_FREIGHT_RATE DECIMAL(10,3)  

ALTER TABLE dbo.FP_FREIGHT_FORM
ADD ANNSER_BLENDED_FREIGHT_RATE DECIMAL(10,3)  



--REVERT
ALTER TABLE FP_FREIGHT_FORM DROP COLUMN HARCAR_BLENDED_FREIGHT_RATE;
ALTER TABLE FP_FREIGHT_FORM DROP COLUMN STKSGM_BLENDED_FREIGHT_RATE;
ALTER TABLE FP_FREIGHT_FORM DROP COLUMN ANNSER_BLENDED_FREIGHT_RATE;


--FP_FREIGHT_FORM_LOG
ALTER TABLE dbo.FP_FREIGHT_FORM_LOG
ADD HARCAR_BLENDED_FREIGHT_RATE DECIMAL(10,3)  

ALTER TABLE dbo.FP_FREIGHT_FORM_LOG
ADD STKSGM_BLENDED_FREIGHT_RATE DECIMAL(10,3)  

ALTER TABLE dbo.FP_FREIGHT_FORM_LOG
ADD ANNSER_BLENDED_FREIGHT_RATE DECIMAL(10,3)  



--REVERT
ALTER TABLE FP_FREIGHT_FORM_LOG DROP COLUMN HARCAR_BLENDED_FREIGHT_RATE;
ALTER TABLE FP_FREIGHT_FORM_LOG DROP COLUMN STKSGM_BLENDED_FREIGHT_RATE;
ALTER TABLE FP_FREIGHT_FORM_LOG DROP COLUMN ANNSER_BLENDED_FREIGHT_RATE;