CREATE TABLE #NOTFULLYBILLED (
    PO_NUMBER VARCHAR(100),
    LO_PURCHASE_ORDER_ID BIGINT,
    LO_LOAD_NUMBER BIGINT
)

CREATE TABLE #PO_LIST (
    LO_PURCHASE_ORDER_ID BIGINT,
    MAX_26PALLETS_FINAL_CALC DECIMAL(10,3)
)

CREATE TABLE #PO_FREIGHT (
    FREIGHT_PAID_PO DECIMAL,
    LO_PURCHASE_ORDER_ID BIGINT,
	LO_LOAD_NUMBER BIGINT,
	BL_BILLING_ID BIGINT,
	PO_NUMBER VARCHAR(50)
)