USE [TMS]
GO

/****** Object:  StoredProcedure [dbo].[SP_FP_TOOL_GET_VENDOR_WHS_LIST]    Script Date: 9/29/2022 12:29:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







-- =============================================
-- Author:		TIM LEWIS
-- Create date: 01/03/2019
-- Description:	GET FORM VENDOR WHS LIST FOR THE FRIEGHT PRICING TOOL

--Modification list
--
--04/30/2019 - TWL - Rename PICKUP_ALLOWANCE to OFFERED_PICKUP_ALLOWANCE
--09/09/2019 - TWL - SUBMIT PARTIAL FORM CHANGE
--08/23/2022 - CEM - Fixed WHS name search
--08/24/2022 - CEM -  Added USE_EAST_BLENDED_FREIGHT_RATE and LOCKED_EAST_BLENDED_FREIGHT_RATE 
-- =============================================
ALTER PROCEDURE [dbo].[SP_FP_TOOL_GET_VENDOR_WHS_LIST]
	@FORM_ID BIGINT = NULL,
	@PICKUP_LOCATION_NAME VARCHAR(250) = NULL,
	@DESTINATION_WHS_NAME VARCHAR(250) = NULL,
	@CROSSDOCK_NAME AS VARCHAR(250) = NULL,
	@METHOD VARCHAR(250) = NULL,
	@Sort_Direction VARCHAR(250) = 'ASC',
	@Sort_Expression VARCHAR(250) = 'WHS_NUMBER'

AS
BEGIN

Select FRM.EAST_BLENDED_FREIGHT_RATE
	 , FRM.GILROC_BLENDED_FREIGHT_RATE
	 , CAST(CASE
				WHEN DW.TMS_WHS_ID IN (1, 114) THEN FRM.GILROC_BLENDED_FREIGHT_RATE
				WHEN DW.TMS_WHS_ID IN (168, 169) THEN FRM.HARCAR_BLENDED_FREIGHT_RATE
				WHEN DW.TMS_WHS_ID IN (160, 214) THEN FRM.STKSGM_BLENDED_FREIGHT_RATE
				WHEN DW.TMS_WHS_ID IN (178, 186) THEN FRM.ANNSER_BLENDED_FREIGHT_RATE
				ELSE NULL
				END AS DECIMAL) AS BLENDED_RATE
	, CAST(CASE
				WHEN DW.TMS_WHS_ID IN (1, 114) THEN 1
				WHEN DW.TMS_WHS_ID IN (168, 169) THEN 2
				WHEN DW.TMS_WHS_ID IN (160, 214) THEN 3
				WHEN DW.TMS_WHS_ID IN (178, 186) THEN 4
				WHEN DW.SOURCE_SYSTEM ='UBS' THEN 5
				ELSE 0
				END AS INT) AS BLENDED_RATE_CODE
	, FRM_VEN.*
INTO #FRM_VEN
from FP_FREIGHT_FORM AS FRM
INNER JOIN FP_FREIGHT_FORM_VENDOR as FRM_VEN
	ON FRM.FP_FREIGHT_FORM_ID = FRM_VEN.FP_FREIGHT_FORM_ID
		AND (FRM_VEN.IS_DELETED IS NULL OR FRM_VEN.IS_DELETED = 0)
LEFT JOIN TMS_WHS AS DW
	ON FRM_VEN.TMS_WHS_ID = DW.TMS_WHS_ID
WHERE FRM.FP_FREIGHT_FORM_ID = @FORM_ID 



	DECLARE @QUERY AS nvarchar(MAX) = ''
	
	SET @QUERY=@QUERY+ '
		select *
		from (
select FRM_VEN.FP_FREIGHT_FORM_ID,
FRM_VEN.FP_FREIGHT_FORM_VENDOR_ID,
METHOD.FP_FF_METHOD_ID,
METHOD.DESCRIPTION AS METHOD,
VEN.TMS_VENDOR_ID,
VEN.NAME AS VENDOR_NAME,
PICKUP.FP_FF_PICKUP_LOCATIONS_ID,
PICKUP.PICKUP_NAME,
PICKUP.ADDRESS AS ORIGIN_ADDRESS,
PICKUP.CITY AS ORIGIN_CITY,
PICKUP.ZIP AS ORIGIN_ZIP,
CW.TMS_WHS_ID AS CROSSDOCK_WHS_ID,
CW.ADDRESS1 AS CROSSDOCK_ADDRESS,
CW.CITY AS CROSSDOCK_CITY,
CW.ZIP AS CROSSDOCK_ZIP,
CW.WHS_NUMBER + '' '' + CW.NAME AS CROSSDOCK_WHS_NAME,
DW.TMS_WHS_ID AS DESTINATION_WHS_ID,
DW.ADDRESS1 AS DESTINATION_WHS_ADDRESS,
DW.CITY AS DESTINATION_WHS_CITY,
DW.ZIP AS DESTINATION_ZIP,
DW.WHS_NUMBER + '' '' + DW.NAME AS DESTINATION_WHS_NAME,
DW.WHS_NUMBER as WHS_NUMBER,
ISNULL(FRM_VEN.CALC_RATE, 0) AS CALC_RATE,
ISNULL(FRM_VEN.CALC_ALL_IN_RATE, 0) AS CALC_ALL_IN_RATE,
RATE.RATE,
ISNULL(FRM_VEN.ALLOWANCE_PER_LB, 0) AS ALLOWANCE_PER_LB,
FRM_VEN.AVERAGE_PALLETS_PER_PO,
FRM_VEN.AVERAGE_PO_UNITS,
--FRM_VEN.AVERAGE_PO_WEIGHT,
((FRM_VEN.AVERAGE_PO_WEIGHT * FRM_VEN.TOTAL_POS) + (ISNULL(LVF.AVG_PO_WEIGHT,0)))/(FRM_VEN.TOTAL_POS + ISNULL(LVF.TOTAL_POS,0)) AS AVERAGE_PO_WEIGHT,
((FRM_VEN.AVERAGE_PO_UNITS * FRM_VEN.TOTAL_POS) + (ISNULL(LVF.AVG_PO_CASES,0)))/(FRM_VEN.TOTAL_POS + ISNULL(LVF.TOTAL_POS,0)) AS AVERAGE_PO_CASES,
((FRM_VEN.AVERAGE_PO_CUBES * FRM_VEN.TOTAL_POS) + (ISNULL(LVF.AVG_PO_CUBES,0)))/(FRM_VEN.TOTAL_POS + ISNULL(LVF.TOTAL_POS,0)) AS AVG_PO_CUBES,
((FRM_VEN.AVERAGE_PALLETS_PER_PO * FRM_VEN.TOTAL_POS) + (ISNULL(LVF.AVG_PALLETS_PO,0)))/(FRM_VEN.TOTAL_POS + ISNULL(LVF.TOTAL_POS,0)) AS AVG_PALLETS_PER_PO,
ISNULL(FRM_VEN.BOOKED_FREIGHT_PER_LB, 0) AS BOOKED_FREIGHT_PER_LB,
ISNULL(FRM_VEN.LANDED_EXPENSE_PER_LB, 0) AS LANDED_EXPENSE_PER_LB,
FRM_VEN.OFFERED_PICKUP_ALLOWANCE,
FRM_VEN.PROJECTED_LOAD_WEIGHT,
FRM_VEN.PROPOSED_ALLOWANCE_PER_LB,
ISNULL(FRM_VEN.PROPOSED_BOOKED_FREIGHT, 0) AS PROPOSED_BOOKED_FREIGHT,
FRM_VEN.PROPOSED_FREIGHT_PER_LB,
ISNULL(FRM_VEN.PROPOSED_PROJECTED_MARGIN, 0) AS PROPOSED_PROJECTED_MARGIN,
ISNULL(FRM_VEN.PROPOSED_TOTAL_ALLOWANCE, 0) AS PROPOSED_TOTAL_ALLOWANCE,
ISNULL(FRM_VEN.TOTAL_MARGIN, 0) AS TOTAL_MARGIN,
ISNULL(FRM_VEN.TOTAL_ALLOWANCE, 0) AS TOTAL_ALLOWANCE,
ISNULL(FRM_VEN.TOTAL_BOOKED_FREIGHT, 0) AS TOTAL_BOOKED_FREIGHT,
ISNULL(FRM_VEN.PROPOSED_TOTAL_EXPENSE, 0) AS PROPOSED_TOTAL_EXPENSE,
FRM_VEN.TOTAL_POS + ISNULL(LVF.TOTAL_POS,0) AS TOTAL_POS,
ISNULL(FRM_VEN.BOOKED_FREIGHT_OVERRIDE, 0) AS BOOKED_FREIGHT_OVERRIDE,
ISNULL(FRM_VEN.PROJECTED_LOAD_WEIGHT_OVERRIDE, 0) AS PROJECTED_LOAD_WEIGHT_OVERRIDE,
FRM_VEN.EAST_BLENDED_FREIGHT_RATE,
CAST(CASE WHEN DW.SOURCE_SYSTEM = ''UBS'' THEN 1 ELSE 0 END AS bit) AS LOCKED_EAST_BLENDED_FREIGHT_RATE,
FRM_VEN.USE_EAST_BLENDED_FREIGHT_RATE,
FRM_VEN.GILROC_BLENDED_FREIGHT_RATE,
CAST(CASE WHEN DW.TMS_WHS_ID IN (1, 114) THEN 1 ELSE 0 END AS bit) AS DISPLAY_GILROC_BLENDED_FREIGHT_RATE,
ISNULL(DW.SOURCE_SYSTEM, '''') AS SOURCE_SYSTEM,
FRM_VEN.EFFECTIVE_DATE,
FRM_VEN.PROCESSED_FLAG,
FRM_VEN.BLENDED_RATE AS BLENDED_RATE,
FRM_VEN.BLENDED_RATE_CODE AS BLENDED_RATE_CODE
from #FRM_VEN AS FRM_VEN
LEFT JOIN FP_FF_METHOD AS METHOD
	ON FRM_VEN.FP_FF_METHOD_ID = METHOD.FP_FF_METHOD_ID 
LEFT JOIN TMS_VENDOR AS VEN
	ON FRM_VEN.TMS_VENDOR_ID = VEN.TMS_VENDOR_ID
LEFT JOIN FP_FF_PICKUP_LOCATIONS AS PICKUP
	ON FRM_VEN.FP_FF_PICKUP_LOCATIONS_ID = PICKUP.FP_FF_PICKUP_LOCATIONS_ID
LEFT JOIN TMS_WHS AS CW
	ON FRM_VEN.CROSSDOCK_WHS_ID = CW.TMS_WHS_ID
LEFT JOIN TMS_WHS AS DW
	ON FRM_VEN.TMS_WHS_ID = DW.TMS_WHS_ID
LEFT JOIN CR_RATE AS RATE
	ON FRM_VEN.CR_RATE_ID = RATE.CR_RATE_ID
LEFT JOIN [dbo].[VIEW_LINKED_VENDOR_FORMS] AS LVF
	ON FRM_VEN.[FP_FREIGHT_FORM_VENDOR_ID] = LVF.MAIN_FORM_ID
 
				WHERE FRM_VEN.FP_FREIGHT_FORM_ID = ' + cast(@FORM_ID AS VARCHAR) 				
				--CONTROL FILTER CRITERIA

				IF(@PICKUP_LOCATION_NAME IS NOT NULL AND @PICKUP_LOCATION_NAME <> '')
					SET @QUERY=@QUERY+  ' WHERE (PICKUP.PICKUP_NAME LIKE ''%'' + '''+cast(@PICKUP_LOCATION_NAME  AS VARCHAR)+''' + ''%'' )'

				IF(@DESTINATION_WHS_NAME IS NOT NULL AND @DESTINATION_WHS_NAME <> '')
					SET @QUERY=@QUERY+  ' AND DW.NAME LIKE '  + '''' + '%' + cast(@DESTINATION_WHS_NAME  AS VARCHAR)+ '%' + '''' 

				IF(@CROSSDOCK_NAME IS NOT NULL AND @CROSSDOCK_NAME <> '')
					SET @QUERY=@QUERY+  ' AND ((CW.WHS_NUMBER + '' '' + CW.NAME) LIKE ''%'' + '''+cast(@CROSSDOCK_NAME  AS VARCHAR)+''' + ''%'' )'

				IF(@METHOD IS NOT NULL AND @METHOD <> '')
					SET @QUERY=@QUERY+  ' AND (METHOD.DESCRIPTION LIKE ''%'' + '''+cast(@METHOD  AS VARCHAR)+''' + ''%'' )'

	--CONTROL SORT CRITERIA
	SET @QUERY=@QUERY+ ') as Result ORDER BY Result.' + @Sort_Expression + ' ' + @Sort_Direction	

    PRINT (@QUERY)
    EXEC sp_executesql @QUERY

END
GO


