CREATE TABLE [dbo].[FP_FREIGHT_FORM]
(
	[FP_FREIGHT_FORM_ID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FP_FF_TYPE_ID] [bigint] NULL,
	[FP_FF_REVIEW_REASON_ID] [bigint] NULL,
	[FP_FF_TEMPERATURE_ID] [bigint] NULL,
	[SUBMIT_DATE] [datetime] NULL,
	[FP_FF_TEMPERATURE_PROTECTION_ID] [bigint] NULL,
	[FP_FF_SPECIAL_CONSIDERATIONS_ID] [bigint] NULL,
	[FP_FF_ALLOWANCE_TYPE_ID] [bigint] NULL,
	[PRODUCT_DESCRIPTION] [varchar](max) NULL,
	[TMS_STATUS_ID] [bigint] NULL,
	[LAWSON_NUMBER] [bigint] NULL,
	[TMS_SRM_ID] [bigint] NULL,
	[LO_LOAD_TEMPERATURES_ID] [bigint] NULL,
	[AUTHORIZER_NAME] [varchar](100) NULL,
	[PHONE_NUMBER] [varchar](20) NULL,
	[FREIGHT_ANALYST_USER_ID] [bigint] NULL,
	[EMAIL] [varchar](100) NULL,
	[IS_HUB_AND_SPOKE] [bit] NULL,
	[IS_HUB_AND_SPOKE_VSP] [bit] NULL,
	[IS_VSP_CROSSDOCK] [bit] NULL,
	[IS_PRICE_LIST_SUBMITTED] [bit] NULL,
	[MARGIN_TARGET] [bit] NULL,
	[PFF_PFH_UP_CHARGE] [bit] NULL,
	[CHILL_FRZ_UP_CHARGE] [bit] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [bigint] NULL,
	[DEFAULT_TOOL_PFF_PFH_UPCHARGE] [decimal](10, 3) NULL,
	[DEFAULT_TOOL_COOLER_FREEZER_UPCHARGE] [decimal](10, 3) NULL,
	[DEFAULT_TOOL_MARGIN_TARGET] [decimal](10, 3) NULL,
	[IS_DELETED] [bit] NULL,
	[SUPPLIER_NAME] [varchar](250) NULL,
	[DEFAULT_TOOL_FUEL_SURCHARGE] [decimal](10, 3) NULL,
	[EAST_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[GILROC_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[SRMC_USER_ID] [bigint] NULL,
	[REJECTED_VSP_FLAG] [bit] NULL,
	[NOTES] [varchar](max) NULL,
	[REJECT_COMMENT] [varchar](max) NULL,
	[IS_EXPLORATORY] [bit] NULL,
	[IS_IMPLIED_RATE] [bit] NULL,
	[DEFAULT_BACKHAUL_PALLET_RATE] [decimal](10, 3) NULL,
	[DEFAULT_CROSSDOCK_PALLET_RATE] [decimal](10, 3) NULL,
	[IBL_NOTES] [varchar](max) NULL,
	[FP_FF_FREIGHT_CHANGE_REASON_ID] [bigint] NULL,
	[UCS_BACKHAUL_PALLET_RATE] [decimal](10, 3) NULL,
	[UCS_CROSSDOCK_PALLET_RATE] [decimal](10, 3) NULL,
	[UCS_TOOL_PFF_PFH_UPCHARGE] [decimal](10, 3) NULL,
	[UCS_TOOL_COOLER_FREEZER_UPCHARGE] [decimal](10, 3) NULL,
	[UCS_TOOL_MARGIN_TARGET] [decimal](10, 3) NULL,
	[UCS_TOOL_FUEL_SURCHARGE] [decimal](10, 3) NULL,
	[UCS_REMIT_NUMBER] [bigint] NULL,
	[HARCAR_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[STKSGM_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[ANNSER_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
 CONSTRAINT [PK_FP_FREIGHT_FORM] PRIMARY KEY CLUSTERED 
(
	[FP_FREIGHT_FORM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_REVIEW_REASON] FOREIGN KEY([FP_FF_REVIEW_REASON_ID])
REFERENCES [dbo].[FP_FF_REVIEW_REASON] ([FP_FF_REVIEW_REASON_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_REVIEW_REASON]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_SPECIAL_CONSIDERATIONS] FOREIGN KEY([FP_FF_SPECIAL_CONSIDERATIONS_ID])
REFERENCES [dbo].[FP_FF_SPECIAL_CONSIDERATIONS] ([FP_FF_SPECIAL_CONSIDERATIONS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_SPECIAL_CONSIDERATIONS]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_TEMPERATURE] FOREIGN KEY([FP_FF_TEMPERATURE_ID])
REFERENCES [dbo].[FP_FF_TEMPERATURE] ([FP_FF_TEMPERATURE_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_TEMPERATURE]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_TEMPERATURE_PROTECTION] FOREIGN KEY([FP_FF_TEMPERATURE_PROTECTION_ID])
REFERENCES [dbo].[FP_FF_TEMPERATURE_PROTECTION] ([FP_FF_TEMPERATURE_PROTECTION_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_TEMPERATURE_PROTECTION]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_TYPE] FOREIGN KEY([FP_FF_TYPE_ID])
REFERENCES [dbo].[FP_FF_TYPE] ([FP_FF_TYPE_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_FP_FF_TYPE]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_LO_LOAD_TEMPERATURES] FOREIGN KEY([LO_LOAD_TEMPERATURES_ID])
REFERENCES [dbo].[LO_LOAD_TEMPERATURES] ([LO_LOAD_TEMPERATURES_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_LO_LOAD_TEMPERATURES]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_SEC_USERS_FREIGHT_ANALYST_USER_ID] FOREIGN KEY([FREIGHT_ANALYST_USER_ID])
REFERENCES [dbo].[SEC_USERS] ([SEC_USERS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_SEC_USERS_FREIGHT_ANALYST_USER_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_TMS_STATUS] FOREIGN KEY([TMS_STATUS_ID])
REFERENCES [dbo].[TMS_STATUS] ([TMS_STATUS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_TMS_STATUS]
GO