CREATE TABLE [dbo].[FP_FREIGHT_FORM_LOG]
(
[FP_FREIGHT_FORM_LOG_ID] [bigint] NOT NULL IDENTITY(1, 1),
[FP_FREIGHT_FORM_ID] [bigint] NOT NULL,
[FP_FF_TYPE_ID] [bigint] NULL,
[SUBMIT_DATE] [datetime] NULL,
[TMS_STATUS_ID] [bigint] NULL,
[MARGIN_TARGET] [bit] NULL,
[PFF_PFH_UP_CHARGE] [bit] NULL,
[CHILL_FRZ_UP_CHARGE] [bit] NULL,
[CREATED_DATE] [datetime] NULL,
[CREATED_BY] [bigint] NULL,
[MODIFIED_DATE] [datetime] NULL,
[MODIFIED_BY] [bigint] NULL,
[TOOL_PFF_PFH_UPCHARGE] [decimal] (10, 3) NULL,
[TOOL_COOLER_FREEZER_UPCHARGE] [decimal] (10, 3) NULL,
[TOOL_MARGIN_TARGET] [decimal] (10, 3) NULL,
[IS_DELETED] [bit] NULL,
[SUPPLIER_NAME] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOOL_FUEL_SURCHARGE] [decimal] (10, 3) NULL,
[EAST_BLENDED_FREIGHT_RATE] [decimal] (10, 3) NULL,
[GILROC_BLENDED_FREIGHT_RATE] [decimal] (10, 3) NULL,
[NEXT_STAGE_COMMENT] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG] ADD CONSTRAINT [PK_FP_FREIGHT_FORM_LOG] PRIMARY KEY CLUSTERED  ([FP_FREIGHT_FORM_LOG_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-FREIGHT_FORM_ID_STATUS_CREATED_DATE] ON [dbo].[FP_FREIGHT_FORM_LOG] ([FP_FREIGHT_FORM_ID], [TMS_STATUS_ID]) INCLUDE ([CREATED_DATE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG] ADD CONSTRAINT [FK_FP_FREIGHT_FORM_LOG_FP_FREIGHT_FORM] FOREIGN KEY ([FP_FREIGHT_FORM_ID]) REFERENCES [dbo].[FP_FREIGHT_FORM] ([FP_FREIGHT_FORM_ID])
GO
ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG] ADD CONSTRAINT [FK_FP_FREIGHT_FORM_LOG_TMS_STATUS] FOREIGN KEY ([TMS_STATUS_ID]) REFERENCES [dbo].[TMS_STATUS] ([TMS_STATUS_ID])
GO
