CREATE TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]
(
	[FP_FREIGHT_FORM_VENDOR_ID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FP_FREIGHT_FORM_ID] [bigint] NOT NULL,
	[TMS_VENDOR_ID] [bigint] NULL,
	[TMS_WHS_ID] [bigint] NULL,
	[FP_FF_PICKUP_LOCATIONS_ID] [bigint] NULL,
	[CR_RATE_ID] [bigint] NULL,
	[FP_FF_CROSSDOCK_STOPS_ID] [bigint] NULL,
	[FP_FF_METHOD_ID] [bigint] NULL,
	[CROSSDOCK_WHS_ID] [bigint] NULL,
	[TOTAL_POS] [decimal](18, 3) NULL,
	[TOTAL_MARGIN] [decimal](18, 3) NULL,
	[TOTAL_ALLOWANCE] [decimal](18, 3) NULL,
	[TOTAL_BOOKED_FREIGHT] [decimal](18, 3) NULL,
	[OFFERED_PICKUP_ALLOWANCE] [decimal](18, 3) NULL,
	[AVERAGE_PO_WEIGHT] [decimal](18, 3) NULL,
	[AVERAGE_PO_UNITS] [decimal](18, 3) NULL,
	[AVERAGE_PALLETS_PER_PO] [decimal](18, 3) NULL,
	[PROPOSED_TOTAL_EXPENSE] [decimal](18, 3) NULL,
	[PROJECTED_LOAD_WEIGHT] [decimal](18, 3) NULL,
	[PROPOSED_ALLOWANCE_PER_LB] [decimal](18, 6) NULL,
	[PROPOSED_FREIGHT_PER_LB] [decimal](18, 6) NULL,
	[PROPOSED_TOTAL_ALLOWANCE] [decimal](18, 3) NULL,
	[PROPOSED_BOOKED_FREIGHT] [decimal](18, 3) NULL,
	[PROPOSED_PROJECTED_MARGIN] [decimal](18, 3) NULL,
	[BOOKED_FREIGHT_PER_LB] [decimal](18, 6) NULL,
	[ALLOWANCE_PER_LB] [decimal](18, 6) NULL,
	[LETTER_FREIGHT_PER_LB] [decimal](18, 6) NULL,
	[LANDED_EXPENSE_PER_LB] [decimal](18, 6) NULL,
	[CALC_RATE] [decimal](18, 3) NULL,
	[CALC_ALL_IN_RATE] [decimal](18, 3) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [bigint] NOT NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [bigint] NULL,
	[IS_DELETED] [bit] NULL,
	[BOOKED_FREIGHT_OVERRIDE] [bit] NULL,
	[PROJECTED_LOAD_WEIGHT_OVERRIDE] [bit] NULL,
	[CURRENT_ALLOWANCE_TYPE_ID] [bigint] NULL,
	[CURRENT_ALLOWANCE] [decimal](10, 3) NULL,
	[PROCESSED_FLAG] [bit] NULL,
	[EFFECTIVE_DATE] [datetime] NULL,
	[CURRENT_FREIGHT_RATE] [decimal](18, 6) NULL,
	[CURRENT_EXPENSE] [decimal](18, 3) NULL,
	[USE_EAST_BLENDED_FREIGHT_RATE] [bit] NOT NULL,
	[AVERAGE_PO_CUBES] [decimal](18, 3) NULL,
 CONSTRAINT [PK_FP_FREIGHT_FORM_VENDOR] PRIMARY KEY CLUSTERED 
(
	[FP_FREIGHT_FORM_VENDOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] ADD  DEFAULT ((0)) FOR [USE_EAST_BLENDED_FREIGHT_RATE]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_FP_FREIGHT_FORM] FOREIGN KEY([FP_FREIGHT_FORM_ID])
REFERENCES [dbo].[FP_FREIGHT_FORM] ([FP_FREIGHT_FORM_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_FP_FREIGHT_FORM]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_FP_FREIGHT_FORM_VENDOR_ID] FOREIGN KEY([FP_FREIGHT_FORM_VENDOR_ID])
REFERENCES [dbo].[FP_FREIGHT_FORM_VENDOR] ([FP_FREIGHT_FORM_VENDOR_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_FP_FREIGHT_FORM_VENDOR_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_LOG_FP_FREIGHT_FORM_VENDOR_ID] FOREIGN KEY([FP_FREIGHT_FORM_VENDOR_ID])
REFERENCES [dbo].[FP_FREIGHT_FORM_VENDOR] ([FP_FREIGHT_FORM_VENDOR_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_LOG_FP_FREIGHT_FORM_VENDOR_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_SEC_USERS] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[SEC_USERS] ([SEC_USERS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_SEC_USERS]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR] FOREIGN KEY([TMS_VENDOR_ID])
REFERENCES [dbo].[TMS_VENDOR] ([TMS_VENDOR_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_CR_RATE_ID] FOREIGN KEY([CR_RATE_ID])
REFERENCES [dbo].[CR_RATE] ([CR_RATE_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_CR_RATE_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_CROSSDOCK_WHS] FOREIGN KEY([CROSSDOCK_WHS_ID])
REFERENCES [dbo].[TMS_WHS] ([TMS_WHS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_CROSSDOCK_WHS]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_FP_FF_CROSSDOCK_STOPS_ID] FOREIGN KEY([FP_FF_CROSSDOCK_STOPS_ID])
REFERENCES [dbo].[FP_FF_CROSSDOCK_STOPS] ([FP_FF_CROSSDOCK_STOPS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_FP_FF_CROSSDOCK_STOPS_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_FP_FF_METHOD_ID] FOREIGN KEY([FP_FF_METHOD_ID])
REFERENCES [dbo].[FP_FF_METHOD] ([FP_FF_METHOD_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_FP_FF_METHOD_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_FP_FF_PICKUP_LOCATIONS_ID] FOREIGN KEY([FP_FF_PICKUP_LOCATIONS_ID])
REFERENCES [dbo].[FP_FF_PICKUP_LOCATIONS] ([FP_FF_PICKUP_LOCATIONS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_FP_FF_PICKUP_LOCATIONS_ID]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_WHS] FOREIGN KEY([TMS_WHS_ID])
REFERENCES [dbo].[TMS_WHS] ([TMS_WHS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_VENDOR] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_VENDOR_TMS_VENDOR_WHS]
GO