CREATE TABLE [dbo].[FP_FREIGHT_FORM_LOG]
(
	[FP_FREIGHT_FORM_LOG_ID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FP_FREIGHT_FORM_ID] [bigint] NOT NULL,
	[FP_FF_TYPE_ID] [bigint] NULL,
	[SUBMIT_DATE] [datetime] NULL,
	[TMS_STATUS_ID] [bigint] NULL,
	[MARGIN_TARGET] [bit] NULL,
	[PFF_PFH_UP_CHARGE] [bit] NULL,
	[CHILL_FRZ_UP_CHARGE] [bit] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [bigint] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [bigint] NULL,
	[DEFAULT_TOOL_PFF_PFH_UPCHARGE] [decimal](10, 3) NULL,
	[DEFAULT_TOOL_COOLER_FREEZER_UPCHARGE] [decimal](10, 3) NULL,
	[DEFAULT_TOOL_MARGIN_TARGET] [decimal](10, 3) NULL,
	[IS_DELETED] [bit] NULL,
	[SUPPLIER_NAME] [varchar](250) NULL,
	[DEFAULT_TOOL_FUEL_SURCHARGE] [decimal](10, 3) NULL,
	[EAST_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[GILROC_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[NEXT_STAGE_COMMENT] [varchar](max) NULL,
	[UCS_BACKHAUL_PALLET_RATE] [decimal](10, 3) NULL,
	[UCS_CROSSDOCK_PALLET_RATE] [decimal](10, 3) NULL,
	[UCS_TOOL_PFF_PFH_UPCHARGE] [decimal](10, 3) NULL,
	[UCS_TOOL_COOLER_FREEZER_UPCHARGE] [decimal](10, 3) NULL,
	[UCS_TOOL_MARGIN_TARGET] [decimal](10, 3) NULL,
	[UCS_TOOL_FUEL_SURCHARGE] [decimal](10, 3) NULL,
	[HARCAR_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[STKSGM_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
	[ANNSER_BLENDED_FREIGHT_RATE] [decimal](10, 3) NULL,
 CONSTRAINT [PK_FP_FREIGHT_FORM_LOG] PRIMARY KEY CLUSTERED 
(
	[FP_FREIGHT_FORM_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_LOG_FP_FREIGHT_FORM] FOREIGN KEY([FP_FREIGHT_FORM_ID])
REFERENCES [dbo].[FP_FREIGHT_FORM] ([FP_FREIGHT_FORM_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_LOG_FP_FREIGHT_FORM]
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG]  WITH CHECK ADD  CONSTRAINT [FK_FP_FREIGHT_FORM_LOG_TMS_STATUS] FOREIGN KEY([TMS_STATUS_ID])
REFERENCES [dbo].[TMS_STATUS] ([TMS_STATUS_ID])
GO

ALTER TABLE [dbo].[FP_FREIGHT_FORM_LOG] CHECK CONSTRAINT [FK_FP_FREIGHT_FORM_LOG_TMS_STATUS]
GO
