USE [TMS]
GO

/****** Object:  StoredProcedure [dbo].[SP_FP_TOOL_CREATE_FORM_LOG]    Script Date: 9/27/2022 10:46:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================  
-- Author:  Tim Lewis  
-- Create date: 01/08/19  
-- Description: Create a log of the Freight Form  
  
--MODIFICATION LIST  
-- 09/09/2019 - TWL - SUBMIT PARTIAL FORM CHANGE  
-- 04/21/2019 - BK  - ADDED NEXT_STAGE_COMMENT
-- 08/09/2022 - BK  - RENAMED ORIGINAL CONFIGS TO DEFAULT, ADDED UCS DEFAULT CONFIGS
-- =============================================  
ALTER PROCEDURE [dbo].[SP_FP_TOOL_CREATE_FORM_LOG]  
 -- Add the parameters for the stored procedure here  
 @FORM_ID BIGINT = NULL,  
 @USER_ID BIGINT = NULL,
 @NEXT_STAGE_COMMENT VARCHAR(MAX) = NULL
AS  
BEGIN  
 -- SET NOCOUNT ON added to prevent extra result sets from  
 -- interfering with SELECT statements.  
 SET NOCOUNT ON;  
  
 INSERT INTO FP_FREIGHT_FORM_LOG (FP_FREIGHT_FORM_ID, FP_FF_TYPE_ID, SUBMIT_DATE, TMS_STATUS_ID, MARGIN_TARGET,   
         PFF_PFH_UP_CHARGE, CREATED_DATE, CREATED_BY, 
		 DEFAULT_TOOL_COOLER_FREEZER_UPCHARGE, DEFAULT_TOOL_MARGIN_TARGET, DEFAULT_TOOL_PFF_PFH_UPCHARGE, DEFAULT_TOOL_FUEL_SURCHARGE, 
		 EAST_BLENDED_FREIGHT_RATE, GILROC_BLENDED_FREIGHT_RATE, NEXT_STAGE_COMMENT,
		 UCS_TOOL_COOLER_FREEZER_UPCHARGE, UCS_TOOL_MARGIN_TARGET, UCS_TOOL_PFF_PFH_UPCHARGE, UCS_TOOL_FUEL_SURCHARGE)  
 SELECT  FORM.FP_FREIGHT_FORM_ID, FORM.FP_FF_TYPE_ID, FORM.SUBMIT_DATE, FORM.TMS_STATUS_ID, FORM.MARGIN_TARGET,   
		FORM.PFF_PFH_UP_CHARGE, GETDATE(), @USER_ID, 
		FORM.DEFAULT_TOOL_COOLER_FREEZER_UPCHARGE, FORM.DEFAULT_TOOL_MARGIN_TARGET, FORM.DEFAULT_TOOL_PFF_PFH_UPCHARGE, FORM.DEFAULT_TOOL_FUEL_SURCHARGE, 
		FORM.EAST_BLENDED_FREIGHT_RATE, FORM.GILROC_BLENDED_FREIGHT_RATE, @NEXT_STAGE_COMMENT,
		FORM.UCS_TOOL_COOLER_FREEZER_UPCHARGE, FORM.UCS_TOOL_MARGIN_TARGET, FORM.UCS_TOOL_PFF_PFH_UPCHARGE,	FORM.UCS_TOOL_FUEL_SURCHARGE  
 FROM FP_FREIGHT_FORM AS FORM  
 WHERE FORM.FP_FREIGHT_FORM_ID = @FORM_ID  
  
 INSERT INTO FP_FREIGHT_FORM_VENDOR_LOG (FP_FREIGHT_FORM_VENDOR_ID, FP_FREIGHT_FORM_ID, TMS_VENDOR_ID,   
    TMS_WHS_ID, FP_FF_PICKUP_LOCATIONS_ID, CR_RATE_ID, FP_FF_CROSSDOCK_STOPS_ID, FP_FF_METHOD_ID,   
    CROSSDOCK_WHS_ID, TOTAL_POS, PROPOSED_TOTAL_EXPENSE, TOTAL_ALLOWANCE, TOTAL_BOOKED_FREIGHT,   
    OFFERED_PICKUP_ALLOWANCE, AVERAGE_PO_WEIGHT, AVERAGE_PO_UNITS, AVERAGE_PALLETS_PER_PO,   
    PROJECTED_LOAD_WEIGHT, PROPOSED_ALLOWANCE_PER_LB, PROPOSED_FREIGHT_PER_LB,   
    PROPOSED_TOTAL_ALLOWANCE, PROPOSED_BOOKED_FREIGHT, TOTAL_MARGIN,   
    PROPOSED_PROJECTED_MARGIN, BOOKED_FREIGHT_PER_LB, ALLOWANCE_PER_LB, LETTER_FREIGHT_PER_LB,   
    LANDED_EXPENSE_PER_LB, CALC_RATE, CALC_ALL_IN_RATE, CREATED_DATE, CREATED_BY, EFFECTIVE_DATE, PROCESSED_FLAG, CURRENT_EXPENSE)  
 SELECT  VEN_WHS.FP_FREIGHT_FORM_VENDOR_ID, VEN_WHS.FP_FREIGHT_FORM_ID, VEN_WHS.TMS_VENDOR_ID,   
   VEN_WHS.TMS_WHS_ID, VEN_WHS.FP_FF_PICKUP_LOCATIONS_ID, VEN_WHS.CR_RATE_ID,   
   VEN_WHS.FP_FF_CROSSDOCK_STOPS_ID, VEN_WHS.FP_FF_METHOD_ID, VEN_WHS.CROSSDOCK_WHS_ID, VEN_WHS.TOTAL_POS,   
   VEN_WHS.PROPOSED_TOTAL_EXPENSE, VEN_WHS.TOTAL_ALLOWANCE, VEN_WHS.TOTAL_BOOKED_FREIGHT, VEN_WHS.OFFERED_PICKUP_ALLOWANCE,   
   VEN_WHS.AVERAGE_PO_WEIGHT, VEN_WHS.AVERAGE_PO_UNITS, VEN_WHS.AVERAGE_PALLETS_PER_PO,   
   VEN_WHS.PROJECTED_LOAD_WEIGHT,   
   VEN_WHS.PROPOSED_ALLOWANCE_PER_LB, VEN_WHS.PROPOSED_FREIGHT_PER_LB, VEN_WHS.PROPOSED_TOTAL_ALLOWANCE,   
   VEN_WHS.PROPOSED_BOOKED_FREIGHT, VEN_WHS.TOTAL_MARGIN,   
   VEN_WHS.PROPOSED_PROJECTED_MARGIN, VEN_WHS.BOOKED_FREIGHT_PER_LB, VEN_WHS.ALLOWANCE_PER_LB,   
   VEN_WHS.LETTER_FREIGHT_PER_LB, VEN_WHS.LANDED_EXPENSE_PER_LB, VEN_WHS.CALC_RATE, VEN_WHS.CALC_ALL_IN_RATE,   
   GETDATE(), @USER_ID, VEN_WHS.EFFECTIVE_DATE, VEN_WHS.PROCESSED_FLAG, VEN_WHS.CURRENT_EXPENSE 
 FROM FP_FREIGHT_FORM_VENDOR AS VEN_WHS  
 WHERE VEN_WHS.FP_FREIGHT_FORM_ID = @FORM_ID  
   AND (VEN_WHS.IS_DELETED IS NULL OR VEN_WHS.IS_DELETED = 0)  
END  
GO


