USE [TMS]
GO

/****** Object:  View [dbo].[VIEW_LINKED_VENDOR_FORMS]    Script Date: 9/29/2022 12:15:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VIEW_LINKED_VENDOR_FORMS]
AS
SELECT        FPFFLF.MAIN_FORM_ID, SUM(FPFFV.TOTAL_POS) AS TOTAL_POS, SUM(FPFFV.AVERAGE_PO_WEIGHT * FPFFV.TOTAL_POS) AS AVG_PO_WEIGHT, SUM(FPFFV.AVERAGE_PO_UNITS * FPFFV.TOTAL_POS) AS AVG_PO_CASES, 
                         FPFFV.AVERAGE_PO_CUBES * FPFFV.TOTAL_POS AS AVG_PO_CUBES, SUM(FPFFV.AVERAGE_PALLETS_PER_PO * FPFFV.TOTAL_POS) AS AVG_PALLETS_PO
FROM            dbo.FP_FF_LINKED_FORMS AS FPFFLF INNER JOIN
                         dbo.FP_FREIGHT_FORM_VENDOR AS FPFFV ON FPFFLF.LINKED_FORM_ID = FPFFV.FP_FREIGHT_FORM_VENDOR_ID
WHERE        (FPFFLF.IS_DELETED = 0 OR
                         FPFFLF.IS_DELETED IS NULL) AND (FPFFV.IS_DELETED = 0 OR
                         FPFFV.IS_DELETED IS NULL)
GROUP BY FPFFLF.MAIN_FORM_ID, FPFFV.AVERAGE_PO_CUBES * FPFFV.TOTAL_POS
GO